// Generated by gencpp from file wheels/cmd_send_manual_instructionResponse.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_SEND_MANUAL_INSTRUCTIONRESPONSE_H
#define WHEELS_MESSAGE_CMD_SEND_MANUAL_INSTRUCTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheels
{
template <class ContainerAllocator>
struct cmd_send_manual_instructionResponse_
{
  typedef cmd_send_manual_instructionResponse_<ContainerAllocator> Type;

  cmd_send_manual_instructionResponse_()
    : nRetCode(0)  {
    }
  cmd_send_manual_instructionResponse_(const ContainerAllocator& _alloc)
    : nRetCode(0)  {
    }



   typedef int32_t _nRetCode_type;
  _nRetCode_type nRetCode;




  typedef boost::shared_ptr< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_send_manual_instructionResponse_

typedef ::wheels::cmd_send_manual_instructionResponse_<std::allocator<void> > cmd_send_manual_instructionResponse;

typedef boost::shared_ptr< ::wheels::cmd_send_manual_instructionResponse > cmd_send_manual_instructionResponsePtr;
typedef boost::shared_ptr< ::wheels::cmd_send_manual_instructionResponse const> cmd_send_manual_instructionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35f948b12c9f4330a3fb0f34d9e1a67f";
  }

  static const char* value(const ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35f948b12c9f4330ULL;
  static const uint64_t static_value2 = 0xa3fb0f34d9e1a67fULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/cmd_send_manual_instructionResponse";
  }

  static const char* value(const ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nRetCode\n\
\n\
";
  }

  static const char* value(const ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nRetCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cmd_send_manual_instructionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::cmd_send_manual_instructionResponse_<ContainerAllocator>& v)
  {
    s << indent << "nRetCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nRetCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_SEND_MANUAL_INSTRUCTIONRESPONSE_H
