// Generated by gencpp from file wheels/cmd_get_navigator_engine_status.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_GET_NAVIGATOR_ENGINE_STATUS_H
#define WHEELS_MESSAGE_CMD_GET_NAVIGATOR_ENGINE_STATUS_H

#include <ros/service_traits.h>


#include <wheels/cmd_get_navigator_engine_statusRequest.h>
#include <wheels/cmd_get_navigator_engine_statusResponse.h>


namespace wheels
{

struct cmd_get_navigator_engine_status
{

typedef cmd_get_navigator_engine_statusRequest Request;
typedef cmd_get_navigator_engine_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_get_navigator_engine_status
} // namespace wheels


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wheels::cmd_get_navigator_engine_status > {
  static const char* value()
  {
    return "6936d01040e4f9f14c640d09de779dbc";
  }

  static const char* value(const ::wheels::cmd_get_navigator_engine_status&) { return value(); }
};

template<>
struct DataType< ::wheels::cmd_get_navigator_engine_status > {
  static const char* value()
  {
    return "wheels/cmd_get_navigator_engine_status";
  }

  static const char* value(const ::wheels::cmd_get_navigator_engine_status&) { return value(); }
};


// service_traits::MD5Sum< ::wheels::cmd_get_navigator_engine_statusRequest> should match 
// service_traits::MD5Sum< ::wheels::cmd_get_navigator_engine_status > 
template<>
struct MD5Sum< ::wheels::cmd_get_navigator_engine_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wheels::cmd_get_navigator_engine_status >::value();
  }
  static const char* value(const ::wheels::cmd_get_navigator_engine_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheels::cmd_get_navigator_engine_statusRequest> should match 
// service_traits::DataType< ::wheels::cmd_get_navigator_engine_status > 
template<>
struct DataType< ::wheels::cmd_get_navigator_engine_statusRequest>
{
  static const char* value()
  {
    return DataType< ::wheels::cmd_get_navigator_engine_status >::value();
  }
  static const char* value(const ::wheels::cmd_get_navigator_engine_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wheels::cmd_get_navigator_engine_statusResponse> should match 
// service_traits::MD5Sum< ::wheels::cmd_get_navigator_engine_status > 
template<>
struct MD5Sum< ::wheels::cmd_get_navigator_engine_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wheels::cmd_get_navigator_engine_status >::value();
  }
  static const char* value(const ::wheels::cmd_get_navigator_engine_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheels::cmd_get_navigator_engine_statusResponse> should match 
// service_traits::DataType< ::wheels::cmd_get_navigator_engine_status > 
template<>
struct DataType< ::wheels::cmd_get_navigator_engine_statusResponse>
{
  static const char* value()
  {
    return DataType< ::wheels::cmd_get_navigator_engine_status >::value();
  }
  static const char* value(const ::wheels::cmd_get_navigator_engine_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_GET_NAVIGATOR_ENGINE_STATUS_H
