// Generated by gencpp from file wheels/cmd_set_car_direction_speed.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_SET_CAR_DIRECTION_SPEED_H
#define WHEELS_MESSAGE_CMD_SET_CAR_DIRECTION_SPEED_H

#include <ros/service_traits.h>


#include <wheels/cmd_set_car_direction_speedRequest.h>
#include <wheels/cmd_set_car_direction_speedResponse.h>


namespace wheels
{

struct cmd_set_car_direction_speed
{

typedef cmd_set_car_direction_speedRequest Request;
typedef cmd_set_car_direction_speedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_set_car_direction_speed
} // namespace wheels


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wheels::cmd_set_car_direction_speed > {
  static const char* value()
  {
    return "3bc718b43ba74a9cbb3a6fbaf985c317";
  }

  static const char* value(const ::wheels::cmd_set_car_direction_speed&) { return value(); }
};

template<>
struct DataType< ::wheels::cmd_set_car_direction_speed > {
  static const char* value()
  {
    return "wheels/cmd_set_car_direction_speed";
  }

  static const char* value(const ::wheels::cmd_set_car_direction_speed&) { return value(); }
};


// service_traits::MD5Sum< ::wheels::cmd_set_car_direction_speedRequest> should match 
// service_traits::MD5Sum< ::wheels::cmd_set_car_direction_speed > 
template<>
struct MD5Sum< ::wheels::cmd_set_car_direction_speedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wheels::cmd_set_car_direction_speed >::value();
  }
  static const char* value(const ::wheels::cmd_set_car_direction_speedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheels::cmd_set_car_direction_speedRequest> should match 
// service_traits::DataType< ::wheels::cmd_set_car_direction_speed > 
template<>
struct DataType< ::wheels::cmd_set_car_direction_speedRequest>
{
  static const char* value()
  {
    return DataType< ::wheels::cmd_set_car_direction_speed >::value();
  }
  static const char* value(const ::wheels::cmd_set_car_direction_speedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wheels::cmd_set_car_direction_speedResponse> should match 
// service_traits::MD5Sum< ::wheels::cmd_set_car_direction_speed > 
template<>
struct MD5Sum< ::wheels::cmd_set_car_direction_speedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wheels::cmd_set_car_direction_speed >::value();
  }
  static const char* value(const ::wheels::cmd_set_car_direction_speedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheels::cmd_set_car_direction_speedResponse> should match 
// service_traits::DataType< ::wheels::cmd_set_car_direction_speed > 
template<>
struct DataType< ::wheels::cmd_set_car_direction_speedResponse>
{
  static const char* value()
  {
    return DataType< ::wheels::cmd_set_car_direction_speed >::value();
  }
  static const char* value(const ::wheels::cmd_set_car_direction_speedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_SET_CAR_DIRECTION_SPEED_H
