// Generated by gencpp from file wheels/cmd_get_one_wheel_status.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUS_H
#define WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUS_H

#include <ros/service_traits.h>


#include <wheels/cmd_get_one_wheel_statusRequest.h>
#include <wheels/cmd_get_one_wheel_statusResponse.h>


namespace wheels
{

struct cmd_get_one_wheel_status
{

typedef cmd_get_one_wheel_statusRequest Request;
typedef cmd_get_one_wheel_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_get_one_wheel_status
} // namespace wheels


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wheels::cmd_get_one_wheel_status > {
  static const char* value()
  {
    return "d68fceb73ca087ead6d51290a67889fa";
  }

  static const char* value(const ::wheels::cmd_get_one_wheel_status&) { return value(); }
};

template<>
struct DataType< ::wheels::cmd_get_one_wheel_status > {
  static const char* value()
  {
    return "wheels/cmd_get_one_wheel_status";
  }

  static const char* value(const ::wheels::cmd_get_one_wheel_status&) { return value(); }
};


// service_traits::MD5Sum< ::wheels::cmd_get_one_wheel_statusRequest> should match 
// service_traits::MD5Sum< ::wheels::cmd_get_one_wheel_status > 
template<>
struct MD5Sum< ::wheels::cmd_get_one_wheel_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wheels::cmd_get_one_wheel_status >::value();
  }
  static const char* value(const ::wheels::cmd_get_one_wheel_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheels::cmd_get_one_wheel_statusRequest> should match 
// service_traits::DataType< ::wheels::cmd_get_one_wheel_status > 
template<>
struct DataType< ::wheels::cmd_get_one_wheel_statusRequest>
{
  static const char* value()
  {
    return DataType< ::wheels::cmd_get_one_wheel_status >::value();
  }
  static const char* value(const ::wheels::cmd_get_one_wheel_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wheels::cmd_get_one_wheel_statusResponse> should match 
// service_traits::MD5Sum< ::wheels::cmd_get_one_wheel_status > 
template<>
struct MD5Sum< ::wheels::cmd_get_one_wheel_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wheels::cmd_get_one_wheel_status >::value();
  }
  static const char* value(const ::wheels::cmd_get_one_wheel_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheels::cmd_get_one_wheel_statusResponse> should match 
// service_traits::DataType< ::wheels::cmd_get_one_wheel_status > 
template<>
struct DataType< ::wheels::cmd_get_one_wheel_statusResponse>
{
  static const char* value()
  {
    return DataType< ::wheels::cmd_get_one_wheel_status >::value();
  }
  static const char* value(const ::wheels::cmd_get_one_wheel_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUS_H
