// Generated by gencpp from file wheels/cmd_set_navigator_engineRequest.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_SET_NAVIGATOR_ENGINEREQUEST_H
#define WHEELS_MESSAGE_CMD_SET_NAVIGATOR_ENGINEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheels
{
template <class ContainerAllocator>
struct cmd_set_navigator_engineRequest_
{
  typedef cmd_set_navigator_engineRequest_<ContainerAllocator> Type;

  cmd_set_navigator_engineRequest_()
    : nNewEngineID(0)
    , strNewEngineDescription()  {
    }
  cmd_set_navigator_engineRequest_(const ContainerAllocator& _alloc)
    : nNewEngineID(0)
    , strNewEngineDescription(_alloc)  {
    }



   typedef uint32_t _nNewEngineID_type;
  _nNewEngineID_type nNewEngineID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strNewEngineDescription_type;
  _strNewEngineDescription_type strNewEngineDescription;




  typedef boost::shared_ptr< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_set_navigator_engineRequest_

typedef ::wheels::cmd_set_navigator_engineRequest_<std::allocator<void> > cmd_set_navigator_engineRequest;

typedef boost::shared_ptr< ::wheels::cmd_set_navigator_engineRequest > cmd_set_navigator_engineRequestPtr;
typedef boost::shared_ptr< ::wheels::cmd_set_navigator_engineRequest const> cmd_set_navigator_engineRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9219ffb36969eb585914fda01a0004d7";
  }

  static const char* value(const ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9219ffb36969eb58ULL;
  static const uint64_t static_value2 = 0x5914fda01a0004d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/cmd_set_navigator_engineRequest";
  }

  static const char* value(const ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 nNewEngineID\n\
string strNewEngineDescription\n\
";
  }

  static const char* value(const ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nNewEngineID);
      stream.next(m.strNewEngineDescription);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cmd_set_navigator_engineRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::cmd_set_navigator_engineRequest_<ContainerAllocator>& v)
  {
    s << indent << "nNewEngineID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nNewEngineID);
    s << indent << "strNewEngineDescription: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strNewEngineDescription);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_SET_NAVIGATOR_ENGINEREQUEST_H
