// Generated by gencpp from file wheels/cmd_set_navigator_engine.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_SET_NAVIGATOR_ENGINE_H
#define WHEELS_MESSAGE_CMD_SET_NAVIGATOR_ENGINE_H

#include <ros/service_traits.h>


#include <wheels/cmd_set_navigator_engineRequest.h>
#include <wheels/cmd_set_navigator_engineResponse.h>


namespace wheels
{

struct cmd_set_navigator_engine
{

typedef cmd_set_navigator_engineRequest Request;
typedef cmd_set_navigator_engineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_set_navigator_engine
} // namespace wheels


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wheels::cmd_set_navigator_engine > {
  static const char* value()
  {
    return "8e305c8b095c5860798ff953a1d04b0e";
  }

  static const char* value(const ::wheels::cmd_set_navigator_engine&) { return value(); }
};

template<>
struct DataType< ::wheels::cmd_set_navigator_engine > {
  static const char* value()
  {
    return "wheels/cmd_set_navigator_engine";
  }

  static const char* value(const ::wheels::cmd_set_navigator_engine&) { return value(); }
};


// service_traits::MD5Sum< ::wheels::cmd_set_navigator_engineRequest> should match 
// service_traits::MD5Sum< ::wheels::cmd_set_navigator_engine > 
template<>
struct MD5Sum< ::wheels::cmd_set_navigator_engineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wheels::cmd_set_navigator_engine >::value();
  }
  static const char* value(const ::wheels::cmd_set_navigator_engineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheels::cmd_set_navigator_engineRequest> should match 
// service_traits::DataType< ::wheels::cmd_set_navigator_engine > 
template<>
struct DataType< ::wheels::cmd_set_navigator_engineRequest>
{
  static const char* value()
  {
    return DataType< ::wheels::cmd_set_navigator_engine >::value();
  }
  static const char* value(const ::wheels::cmd_set_navigator_engineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wheels::cmd_set_navigator_engineResponse> should match 
// service_traits::MD5Sum< ::wheels::cmd_set_navigator_engine > 
template<>
struct MD5Sum< ::wheels::cmd_set_navigator_engineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wheels::cmd_set_navigator_engine >::value();
  }
  static const char* value(const ::wheels::cmd_set_navigator_engineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheels::cmd_set_navigator_engineResponse> should match 
// service_traits::DataType< ::wheels::cmd_set_navigator_engine > 
template<>
struct DataType< ::wheels::cmd_set_navigator_engineResponse>
{
  static const char* value()
  {
    return DataType< ::wheels::cmd_set_navigator_engine >::value();
  }
  static const char* value(const ::wheels::cmd_set_navigator_engineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_SET_NAVIGATOR_ENGINE_H
