// Generated by gencpp from file wheels/cmd_get_one_wheel_statusRequest.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUSREQUEST_H
#define WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheels
{
template <class ContainerAllocator>
struct cmd_get_one_wheel_statusRequest_
{
  typedef cmd_get_one_wheel_statusRequest_<ContainerAllocator> Type;

  cmd_get_one_wheel_statusRequest_()
    : nWheelID(0)  {
    }
  cmd_get_one_wheel_statusRequest_(const ContainerAllocator& _alloc)
    : nWheelID(0)  {
    }



   typedef uint32_t _nWheelID_type;
  _nWheelID_type nWheelID;




  typedef boost::shared_ptr< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_get_one_wheel_statusRequest_

typedef ::wheels::cmd_get_one_wheel_statusRequest_<std::allocator<void> > cmd_get_one_wheel_statusRequest;

typedef boost::shared_ptr< ::wheels::cmd_get_one_wheel_statusRequest > cmd_get_one_wheel_statusRequestPtr;
typedef boost::shared_ptr< ::wheels::cmd_get_one_wheel_statusRequest const> cmd_get_one_wheel_statusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d352e28eb94515d4f0db5ca94dd1ac5";
  }

  static const char* value(const ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d352e28eb94515dULL;
  static const uint64_t static_value2 = 0x4f0db5ca94dd1ac5ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/cmd_get_one_wheel_statusRequest";
  }

  static const char* value(const ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 nWheelID\n\
";
  }

  static const char* value(const ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nWheelID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cmd_get_one_wheel_statusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::cmd_get_one_wheel_statusRequest_<ContainerAllocator>& v)
  {
    s << indent << "nWheelID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nWheelID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUSREQUEST_H
