// Generated by gencpp from file wheels/cmd_get_navigator_engine_statusResponse.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_GET_NAVIGATOR_ENGINE_STATUSRESPONSE_H
#define WHEELS_MESSAGE_CMD_GET_NAVIGATOR_ENGINE_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheels
{
template <class ContainerAllocator>
struct cmd_get_navigator_engine_statusResponse_
{
  typedef cmd_get_navigator_engine_statusResponse_<ContainerAllocator> Type;

  cmd_get_navigator_engine_statusResponse_()
    : nActiveEngineID(0)
    , strActiveEngineDescription()
    , nRetCode(0)  {
    }
  cmd_get_navigator_engine_statusResponse_(const ContainerAllocator& _alloc)
    : nActiveEngineID(0)
    , strActiveEngineDescription(_alloc)
    , nRetCode(0)  {
    }



   typedef uint32_t _nActiveEngineID_type;
  _nActiveEngineID_type nActiveEngineID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strActiveEngineDescription_type;
  _strActiveEngineDescription_type strActiveEngineDescription;

   typedef int32_t _nRetCode_type;
  _nRetCode_type nRetCode;




  typedef boost::shared_ptr< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_get_navigator_engine_statusResponse_

typedef ::wheels::cmd_get_navigator_engine_statusResponse_<std::allocator<void> > cmd_get_navigator_engine_statusResponse;

typedef boost::shared_ptr< ::wheels::cmd_get_navigator_engine_statusResponse > cmd_get_navigator_engine_statusResponsePtr;
typedef boost::shared_ptr< ::wheels::cmd_get_navigator_engine_statusResponse const> cmd_get_navigator_engine_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6936d01040e4f9f14c640d09de779dbc";
  }

  static const char* value(const ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6936d01040e4f9f1ULL;
  static const uint64_t static_value2 = 0x4c640d09de779dbcULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/cmd_get_navigator_engine_statusResponse";
  }

  static const char* value(const ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 nActiveEngineID\n\
string strActiveEngineDescription\n\
int32 nRetCode\n\
\n\
";
  }

  static const char* value(const ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nActiveEngineID);
      stream.next(m.strActiveEngineDescription);
      stream.next(m.nRetCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cmd_get_navigator_engine_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::cmd_get_navigator_engine_statusResponse_<ContainerAllocator>& v)
  {
    s << indent << "nActiveEngineID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nActiveEngineID);
    s << indent << "strActiveEngineDescription: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strActiveEngineDescription);
    s << indent << "nRetCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nRetCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_GET_NAVIGATOR_ENGINE_STATUSRESPONSE_H
