// Generated by gencpp from file wheels/cmd_send_manual_instructionRequest.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_SEND_MANUAL_INSTRUCTIONREQUEST_H
#define WHEELS_MESSAGE_CMD_SEND_MANUAL_INSTRUCTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheels
{
template <class ContainerAllocator>
struct cmd_send_manual_instructionRequest_
{
  typedef cmd_send_manual_instructionRequest_<ContainerAllocator> Type;

  cmd_send_manual_instructionRequest_()
    : nManualInstruction(0)  {
    }
  cmd_send_manual_instructionRequest_(const ContainerAllocator& _alloc)
    : nManualInstruction(0)  {
    }



   typedef int32_t _nManualInstruction_type;
  _nManualInstruction_type nManualInstruction;




  typedef boost::shared_ptr< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_send_manual_instructionRequest_

typedef ::wheels::cmd_send_manual_instructionRequest_<std::allocator<void> > cmd_send_manual_instructionRequest;

typedef boost::shared_ptr< ::wheels::cmd_send_manual_instructionRequest > cmd_send_manual_instructionRequestPtr;
typedef boost::shared_ptr< ::wheels::cmd_send_manual_instructionRequest const> cmd_send_manual_instructionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48fe35c002c140dd58896642360d66f6";
  }

  static const char* value(const ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48fe35c002c140ddULL;
  static const uint64_t static_value2 = 0x58896642360d66f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/cmd_send_manual_instructionRequest";
  }

  static const char* value(const ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nManualInstruction\n\
";
  }

  static const char* value(const ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nManualInstruction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cmd_send_manual_instructionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::cmd_send_manual_instructionRequest_<ContainerAllocator>& v)
  {
    s << indent << "nManualInstruction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nManualInstruction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_SEND_MANUAL_INSTRUCTIONREQUEST_H
