// Generated by gencpp from file wheels/cmd_get_one_wheel_statusResponse.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUSRESPONSE_H
#define WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheels
{
template <class ContainerAllocator>
struct cmd_get_one_wheel_statusResponse_
{
  typedef cmd_get_one_wheel_statusResponse_<ContainerAllocator> Type;

  cmd_get_one_wheel_statusResponse_()
    : nWheelDirection(0)
    , nWheelSpeed(0)
    , nWheelHealthStatus(0)
    , nRetCode(0)  {
    }
  cmd_get_one_wheel_statusResponse_(const ContainerAllocator& _alloc)
    : nWheelDirection(0)
    , nWheelSpeed(0)
    , nWheelHealthStatus(0)
    , nRetCode(0)  {
    }



   typedef uint32_t _nWheelDirection_type;
  _nWheelDirection_type nWheelDirection;

   typedef uint32_t _nWheelSpeed_type;
  _nWheelSpeed_type nWheelSpeed;

   typedef uint32_t _nWheelHealthStatus_type;
  _nWheelHealthStatus_type nWheelHealthStatus;

   typedef int32_t _nRetCode_type;
  _nRetCode_type nRetCode;




  typedef boost::shared_ptr< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_get_one_wheel_statusResponse_

typedef ::wheels::cmd_get_one_wheel_statusResponse_<std::allocator<void> > cmd_get_one_wheel_statusResponse;

typedef boost::shared_ptr< ::wheels::cmd_get_one_wheel_statusResponse > cmd_get_one_wheel_statusResponsePtr;
typedef boost::shared_ptr< ::wheels::cmd_get_one_wheel_statusResponse const> cmd_get_one_wheel_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0e5283a5f5329d6928226b5d620136f";
  }

  static const char* value(const ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0e5283a5f5329d6ULL;
  static const uint64_t static_value2 = 0x928226b5d620136fULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/cmd_get_one_wheel_statusResponse";
  }

  static const char* value(const ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 nWheelDirection\n\
uint32 nWheelSpeed\n\
uint32 nWheelHealthStatus\n\
int32 nRetCode\n\
\n\
";
  }

  static const char* value(const ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nWheelDirection);
      stream.next(m.nWheelSpeed);
      stream.next(m.nWheelHealthStatus);
      stream.next(m.nRetCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cmd_get_one_wheel_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::cmd_get_one_wheel_statusResponse_<ContainerAllocator>& v)
  {
    s << indent << "nWheelDirection: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nWheelDirection);
    s << indent << "nWheelSpeed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nWheelSpeed);
    s << indent << "nWheelHealthStatus: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nWheelHealthStatus);
    s << indent << "nRetCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nRetCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_CMD_GET_ONE_WHEEL_STATUSRESPONSE_H
