// Generated by gencpp from file wheels/navigator_engine_status.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_NAVIGATOR_ENGINE_STATUS_H
#define WHEELS_MESSAGE_NAVIGATOR_ENGINE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wheels
{
template <class ContainerAllocator>
struct navigator_engine_status_
{
  typedef navigator_engine_status_<ContainerAllocator> Type;

  navigator_engine_status_()
    : header()
    , nActiveEngineID(0)
    , strActiveEngineDescription()  {
    }
  navigator_engine_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nActiveEngineID(0)
    , strActiveEngineDescription(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _nActiveEngineID_type;
  _nActiveEngineID_type nActiveEngineID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strActiveEngineDescription_type;
  _strActiveEngineDescription_type strActiveEngineDescription;




  typedef boost::shared_ptr< ::wheels::navigator_engine_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::navigator_engine_status_<ContainerAllocator> const> ConstPtr;

}; // struct navigator_engine_status_

typedef ::wheels::navigator_engine_status_<std::allocator<void> > navigator_engine_status;

typedef boost::shared_ptr< ::wheels::navigator_engine_status > navigator_engine_statusPtr;
typedef boost::shared_ptr< ::wheels::navigator_engine_status const> navigator_engine_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::navigator_engine_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::navigator_engine_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::navigator_engine_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::navigator_engine_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::navigator_engine_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::navigator_engine_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::navigator_engine_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::navigator_engine_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::navigator_engine_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b58306f136fb7e7ce1f37a683a5ac9f4";
  }

  static const char* value(const ::wheels::navigator_engine_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb58306f136fb7e7cULL;
  static const uint64_t static_value2 = 0xe1f37a683a5ac9f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::navigator_engine_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/navigator_engine_status";
  }

  static const char* value(const ::wheels::navigator_engine_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::navigator_engine_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 nActiveEngineID\n\
string strActiveEngineDescription\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::wheels::navigator_engine_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::navigator_engine_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nActiveEngineID);
      stream.next(m.strActiveEngineDescription);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct navigator_engine_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::navigator_engine_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::navigator_engine_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nActiveEngineID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nActiveEngineID);
    s << indent << "strActiveEngineDescription: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strActiveEngineDescription);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_NAVIGATOR_ENGINE_STATUS_H
