// Generated by gencpp from file wheels/set_car_direction_speedGoal.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_SET_CAR_DIRECTION_SPEEDGOAL_H
#define WHEELS_MESSAGE_SET_CAR_DIRECTION_SPEEDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheels
{
template <class ContainerAllocator>
struct set_car_direction_speedGoal_
{
  typedef set_car_direction_speedGoal_<ContainerAllocator> Type;

  set_car_direction_speedGoal_()
    : nNewDirection(0)
    , nNewSpeed(0)  {
    }
  set_car_direction_speedGoal_(const ContainerAllocator& _alloc)
    : nNewDirection(0)
    , nNewSpeed(0)  {
    }



   typedef uint32_t _nNewDirection_type;
  _nNewDirection_type nNewDirection;

   typedef uint32_t _nNewSpeed_type;
  _nNewSpeed_type nNewSpeed;




  typedef boost::shared_ptr< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> const> ConstPtr;

}; // struct set_car_direction_speedGoal_

typedef ::wheels::set_car_direction_speedGoal_<std::allocator<void> > set_car_direction_speedGoal;

typedef boost::shared_ptr< ::wheels::set_car_direction_speedGoal > set_car_direction_speedGoalPtr;
typedef boost::shared_ptr< ::wheels::set_car_direction_speedGoal const> set_car_direction_speedGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::set_car_direction_speedGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9cc4e6dec1e6d884ceb90732596657a";
  }

  static const char* value(const ::wheels::set_car_direction_speedGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9cc4e6dec1e6d88ULL;
  static const uint64_t static_value2 = 0x4ceb90732596657aULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/set_car_direction_speedGoal";
  }

  static const char* value(const ::wheels::set_car_direction_speedGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#define the goal\n\
uint32 nNewDirection\n\
uint32 nNewSpeed\n\
";
  }

  static const char* value(const ::wheels::set_car_direction_speedGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nNewDirection);
      stream.next(m.nNewSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct set_car_direction_speedGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::set_car_direction_speedGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::set_car_direction_speedGoal_<ContainerAllocator>& v)
  {
    s << indent << "nNewDirection: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nNewDirection);
    s << indent << "nNewSpeed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nNewSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_SET_CAR_DIRECTION_SPEEDGOAL_H
