// Generated by gencpp from file wheels/set_car_direction_speedAction.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_SET_CAR_DIRECTION_SPEEDACTION_H
#define WHEELS_MESSAGE_SET_CAR_DIRECTION_SPEEDACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <wheels/set_car_direction_speedActionGoal.h>
#include <wheels/set_car_direction_speedActionResult.h>
#include <wheels/set_car_direction_speedActionFeedback.h>

namespace wheels
{
template <class ContainerAllocator>
struct set_car_direction_speedAction_
{
  typedef set_car_direction_speedAction_<ContainerAllocator> Type;

  set_car_direction_speedAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  set_car_direction_speedAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
    }



   typedef  ::wheels::set_car_direction_speedActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::wheels::set_car_direction_speedActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::wheels::set_car_direction_speedActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;




  typedef boost::shared_ptr< ::wheels::set_car_direction_speedAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::set_car_direction_speedAction_<ContainerAllocator> const> ConstPtr;

}; // struct set_car_direction_speedAction_

typedef ::wheels::set_car_direction_speedAction_<std::allocator<void> > set_car_direction_speedAction;

typedef boost::shared_ptr< ::wheels::set_car_direction_speedAction > set_car_direction_speedActionPtr;
typedef boost::shared_ptr< ::wheels::set_car_direction_speedAction const> set_car_direction_speedActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::set_car_direction_speedAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::set_car_direction_speedAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::set_car_direction_speedAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::set_car_direction_speedAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea49bcc42a5411e98da16bffd8d0dc02";
  }

  static const char* value(const ::wheels::set_car_direction_speedAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea49bcc42a5411e9ULL;
  static const uint64_t static_value2 = 0x8da16bffd8d0dc02ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/set_car_direction_speedAction";
  }

  static const char* value(const ::wheels::set_car_direction_speedAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
set_car_direction_speedActionGoal action_goal\n\
set_car_direction_speedActionResult action_result\n\
set_car_direction_speedActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: wheels/set_car_direction_speedActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
set_car_direction_speedGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: wheels/set_car_direction_speedGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#define the goal\n\
uint32 nNewDirection\n\
uint32 nNewSpeed\n\
\n\
================================================================================\n\
MSG: wheels/set_car_direction_speedActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
set_car_direction_speedResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: wheels/set_car_direction_speedResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#define the result\n\
uint32 nLastDirection\n\
uint32 nLastSpeed\n\
int32 nRetCode\n\
\n\
================================================================================\n\
MSG: wheels/set_car_direction_speedActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
set_car_direction_speedFeedback feedback\n\
\n\
================================================================================\n\
MSG: wheels/set_car_direction_speedFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#define the feedback message\n\
uint32 nCurrentDirection\n\
uint32 nCurrentSpeed\n\
int32 nRetCode\n\
\n\
";
  }

  static const char* value(const ::wheels::set_car_direction_speedAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct set_car_direction_speedAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::set_car_direction_speedAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::set_car_direction_speedAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::wheels::set_car_direction_speedActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::wheels::set_car_direction_speedActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::wheels::set_car_direction_speedActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_SET_CAR_DIRECTION_SPEEDACTION_H
