// Generated by gencpp from file wheels/wheels_status.msg
// DO NOT EDIT!


#ifndef WHEELS_MESSAGE_WHEELS_STATUS_H
#define WHEELS_MESSAGE_WHEELS_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wheels
{
template <class ContainerAllocator>
struct wheels_status_
{
  typedef wheels_status_<ContainerAllocator> Type;

  wheels_status_()
    : header()
    , nRightWheelHealthStatus(0)
    , nRightWheelDirection(0)
    , nRightWheelSpeed(0)
    , nLeftWheelHealthStatus(0)
    , nLeftWheelDirection(0)
    , nLeftWheelSpeed(0)  {
    }
  wheels_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nRightWheelHealthStatus(0)
    , nRightWheelDirection(0)
    , nRightWheelSpeed(0)
    , nLeftWheelHealthStatus(0)
    , nLeftWheelDirection(0)
    , nLeftWheelSpeed(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _nRightWheelHealthStatus_type;
  _nRightWheelHealthStatus_type nRightWheelHealthStatus;

   typedef uint32_t _nRightWheelDirection_type;
  _nRightWheelDirection_type nRightWheelDirection;

   typedef uint32_t _nRightWheelSpeed_type;
  _nRightWheelSpeed_type nRightWheelSpeed;

   typedef uint32_t _nLeftWheelHealthStatus_type;
  _nLeftWheelHealthStatus_type nLeftWheelHealthStatus;

   typedef uint32_t _nLeftWheelDirection_type;
  _nLeftWheelDirection_type nLeftWheelDirection;

   typedef uint32_t _nLeftWheelSpeed_type;
  _nLeftWheelSpeed_type nLeftWheelSpeed;




  typedef boost::shared_ptr< ::wheels::wheels_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheels::wheels_status_<ContainerAllocator> const> ConstPtr;

}; // struct wheels_status_

typedef ::wheels::wheels_status_<std::allocator<void> > wheels_status;

typedef boost::shared_ptr< ::wheels::wheels_status > wheels_statusPtr;
typedef boost::shared_ptr< ::wheels::wheels_status const> wheels_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheels::wheels_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheels::wheels_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheels

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'wheels': ['/home/alex/RaspberryPiProject/roscar/src/wheels/msg', '/home/alex/RaspberryPiProject/roscar/devel/share/wheels/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheels::wheels_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheels::wheels_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::wheels_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheels::wheels_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::wheels_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheels::wheels_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheels::wheels_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9e1eea3ebd2a2cbb068d478af7927a1";
  }

  static const char* value(const ::wheels::wheels_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9e1eea3ebd2a2cbULL;
  static const uint64_t static_value2 = 0xb068d478af7927a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheels::wheels_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheels/wheels_status";
  }

  static const char* value(const ::wheels::wheels_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheels::wheels_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 nRightWheelHealthStatus\n\
uint32 nRightWheelDirection\n\
uint32 nRightWheelSpeed\n\
uint32 nLeftWheelHealthStatus\n\
uint32 nLeftWheelDirection\n\
uint32 nLeftWheelSpeed\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::wheels::wheels_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheels::wheels_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nRightWheelHealthStatus);
      stream.next(m.nRightWheelDirection);
      stream.next(m.nRightWheelSpeed);
      stream.next(m.nLeftWheelHealthStatus);
      stream.next(m.nLeftWheelDirection);
      stream.next(m.nLeftWheelSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct wheels_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheels::wheels_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheels::wheels_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nRightWheelHealthStatus: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nRightWheelHealthStatus);
    s << indent << "nRightWheelDirection: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nRightWheelDirection);
    s << indent << "nRightWheelSpeed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nRightWheelSpeed);
    s << indent << "nLeftWheelHealthStatus: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nLeftWheelHealthStatus);
    s << indent << "nLeftWheelDirection: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nLeftWheelDirection);
    s << indent << "nLeftWheelSpeed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nLeftWheelSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELS_MESSAGE_WHEELS_STATUS_H
