(cl:in-package wheels-srv)
(cl:export '(NNEWENGINEID-VAL
          NNEWENGINEID
          STRNEWENGINEDESCRIPTION-VAL
          STRNEWENGINEDESCRIPTION
          NLASTENGINEID-VAL
          NLASTENGINEID
          STRLASTENGINEDESCRIPTION-VAL
          STRLASTENGINEDESCRIPTION
          NACTIVEENGINEID-VAL
          NACTIVEENGINEID
          STRACTIVEENGINEDESCRIPTION-VAL
          STRACTIVEENGINEDESCRIPTION
          NRETCODE-VAL
          NRETCODE
))