(cl:defpackage wheels-srv
  (:use )
  (:export
   "CMD_GET_ONE_WHEEL_STATUS"
   "<CMD_GET_ONE_WHEEL_STATUS-REQUEST>"
   "CMD_GET_ONE_WHEEL_STATUS-REQUEST"
   "<CMD_GET_ONE_WHEEL_STATUS-RESPONSE>"
   "CMD_GET_ONE_WHEEL_STATUS-RESPONSE"
   "CMD_SET_CAR_DIRECTION_SPEED"
   "<CMD_SET_CAR_DIRECTION_SPEED-REQUEST>"
   "CMD_SET_CAR_DIRECTION_SPEED-REQUEST"
   "<CMD_SET_CAR_DIRECTION_SPEED-RESPONSE>"
   "CMD_SET_CAR_DIRECTION_SPEED-RESPONSE"
  ))

