"""autogenerated by genpy from wheels/set_car_direction_speedFeedback.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class set_car_direction_speedFeedback(genpy.Message):
  _md5sum = "b0c6e9edd70dc4e3074ed473e625107a"
  _type = "wheels/set_car_direction_speedFeedback"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#define the feedback message
uint32 nCurrentDirection
uint32 nCurrentSpeed
int32 nRetCode


"""
  __slots__ = ['nCurrentDirection','nCurrentSpeed','nRetCode']
  _slot_types = ['uint32','uint32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       nCurrentDirection,nCurrentSpeed,nRetCode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(set_car_direction_speedFeedback, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.nCurrentDirection is None:
        self.nCurrentDirection = 0
      if self.nCurrentSpeed is None:
        self.nCurrentSpeed = 0
      if self.nRetCode is None:
        self.nRetCode = 0
    else:
      self.nCurrentDirection = 0
      self.nCurrentSpeed = 0
      self.nRetCode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2Ii.pack(_x.nCurrentDirection, _x.nCurrentSpeed, _x.nRetCode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.nCurrentDirection, _x.nCurrentSpeed, _x.nRetCode,) = _struct_2Ii.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2Ii.pack(_x.nCurrentDirection, _x.nCurrentSpeed, _x.nRetCode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.nCurrentDirection, _x.nCurrentSpeed, _x.nRetCode,) = _struct_2Ii.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2Ii = struct.Struct("<2Ii")
