(cl:defpackage wheels-msg
  (:use )
  (:export
   "<NAVIGATOR_ENGINE_STATUS>"
   "NAVIGATOR_ENGINE_STATUS"
   "<WHEELS_STATUS>"
   "WHEELS_STATUS"
   "<SET_CAR_DIRECTION_SPEEDACTION>"
   "SET_CAR_DIRECTION_SPEEDACTION"
   "<SET_CAR_DIRECTION_SPEEDGOAL>"
   "SET_CAR_DIRECTION_SPEEDGOAL"
   "<SET_CAR_DIRECTION_SPEEDFEEDBACK>"
   "SET_CAR_DIRECTION_SPEEDFEEDBACK"
   "<SET_CAR_DIRECTION_SPEEDACTIONGOAL>"
   "SET_CAR_DIRECTION_SPEEDACTIONGOAL"
   "<SET_CAR_DIRECTION_SPEEDACTIONRESULT>"
   "SET_CAR_DIRECTION_SPEEDACTIONRESULT"
   "<SET_CAR_DIRECTION_SPEEDACTIONFEEDBACK>"
   "SET_CAR_DIRECTION_SPEEDACTIONFEEDBACK"
   "<SET_CAR_DIRECTION_SPEEDRESULT>"
   "SET_CAR_DIRECTION_SPEEDRESULT"
  ))

