; Auto-generated. Do not edit!


(cl:in-package wheels-msg)


;//! \htmlinclude set_car_direction_speedGoal.msg.html

(cl:defclass <set_car_direction_speedGoal> (roslisp-msg-protocol:ros-message)
  ((nNewDirection
    :reader nNewDirection
    :initarg :nNewDirection
    :type cl:integer
    :initform 0)
   (nNewSpeed
    :reader nNewSpeed
    :initarg :nNewSpeed
    :type cl:integer
    :initform 0))
)

(cl:defclass set_car_direction_speedGoal (<set_car_direction_speedGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <set_car_direction_speedGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'set_car_direction_speedGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name wheels-msg:<set_car_direction_speedGoal> is deprecated: use wheels-msg:set_car_direction_speedGoal instead.")))

(cl:ensure-generic-function 'nNewDirection-val :lambda-list '(m))
(cl:defmethod nNewDirection-val ((m <set_car_direction_speedGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader wheels-msg:nNewDirection-val is deprecated.  Use wheels-msg:nNewDirection instead.")
  (nNewDirection m))

(cl:ensure-generic-function 'nNewSpeed-val :lambda-list '(m))
(cl:defmethod nNewSpeed-val ((m <set_car_direction_speedGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader wheels-msg:nNewSpeed-val is deprecated.  Use wheels-msg:nNewSpeed instead.")
  (nNewSpeed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <set_car_direction_speedGoal>) ostream)
  "Serializes a message object of type '<set_car_direction_speedGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'nNewDirection)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'nNewDirection)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'nNewDirection)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'nNewDirection)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'nNewSpeed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'nNewSpeed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'nNewSpeed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'nNewSpeed)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <set_car_direction_speedGoal>) istream)
  "Deserializes a message object of type '<set_car_direction_speedGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'nNewDirection)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'nNewDirection)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'nNewDirection)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'nNewDirection)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'nNewSpeed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'nNewSpeed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'nNewSpeed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'nNewSpeed)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<set_car_direction_speedGoal>)))
  "Returns string type for a message object of type '<set_car_direction_speedGoal>"
  "wheels/set_car_direction_speedGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'set_car_direction_speedGoal)))
  "Returns string type for a message object of type 'set_car_direction_speedGoal"
  "wheels/set_car_direction_speedGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<set_car_direction_speedGoal>)))
  "Returns md5sum for a message object of type '<set_car_direction_speedGoal>"
  "f9cc4e6dec1e6d884ceb90732596657a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'set_car_direction_speedGoal)))
  "Returns md5sum for a message object of type 'set_car_direction_speedGoal"
  "f9cc4e6dec1e6d884ceb90732596657a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<set_car_direction_speedGoal>)))
  "Returns full string definition for message of type '<set_car_direction_speedGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define the goal~%uint32 nNewDirection~%uint32 nNewSpeed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'set_car_direction_speedGoal)))
  "Returns full string definition for message of type 'set_car_direction_speedGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define the goal~%uint32 nNewDirection~%uint32 nNewSpeed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <set_car_direction_speedGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <set_car_direction_speedGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'set_car_direction_speedGoal
    (cl:cons ':nNewDirection (nNewDirection msg))
    (cl:cons ':nNewSpeed (nNewSpeed msg))
))
